#Publisher config

#General parameters
queueservice: 'on'
batch_size: 300
push_interval: 300000
polling_interval: 10000

#Rabbitmq server parameters
host: 'ps-mexchg-west.es.net'
username: "abc"
password: "xyz"
vhost: "perfsonar"

#Rabbitmq exchange parameters
exchange_name: "sls_exchange1"
exchange_type: "fanout"
durable: true
