#Queue
queue:
    queueservice: 'off'
    host: 
        - 'localhost'
    port: 61616
    protocol: 'tcp'
    batch_size: 500
    push_interval: 90

#Messages
message:
    persistent: false
    ttl: 120
